# This file describes the keymaps that will be built by the GitHub Actions CI.
# Most options are defined by CMake arguments, see definitions in keymaps/quacken.keymap.
# Each keymap is an "artifact", whose name goes as follows:
#
#   `quacken_[variant]_[layout]_[hold_taps]_[options]`
#
# - [variant]:
#   - flex (integrated rp2040 micro-controller)
#   - zero (promicro, you’ll have to update the `board` field to have your actual promicro board)
#
# - [layout]: (qwerty when omitted)
#   - `ergol`     (KB_LAYOUT_ERGOL)
#   - `azerty`    (KB_LAYOUT_AZERTY)
#   - `lafayette` (KB_LAYOUT_QWERTY_LAFAYETTE)
#   - ... probably more to come in the future
#
# - [hold_taps]: (hrm when omitted)
#   - `ez`  (HT_NONE): no hold-taps, VERY simple config (recommended for absolute beginners)
#   - `tt`  (HT_THUMB_TAPS): hold-taps on thumb keys (recommended for beginner/intermediate users)
#   - `hrm` (HT_HOME_ROW_MODS): homerow-mods enabled and refactored thumb keys (default)
#   - `2tk` (HT_TWO_THUMB_KEYS): hrm enabled and only two thumb keys used per thumb (needed if you use a rotary encoder)
#
# - [options]:
#   - `vim` (VIM_NAVIGATION): use two `VimNav` and `NumRow` layers instead of `NavNum`
#   - `left` (LEFT_HAND_SPACE): space on the left thumb, backspace on the right thumb
#   - `shift` (HRM_SHIFT): add shift as a pinky homerow-mod

include:
    # Default config
  - board: xiao_ble
    shield: totem_left
    artifact-name: totem_default_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: totem_right
    artifact-name: totem_default_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DCONFIG_ZMK_STUDIO=y


    # Ergo-L + Vim + hrm_shift config
  - board: xiao_ble
    shield: totem_left
    artifact-name: totem_ergol_vim_shift_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: totem_right
    artifact-name: totem_ergol_vim_shift_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Vim + 2tk config
  - board: xiao_ble
    shield: totem_left
    artifact-name: totem_ergol_2tk_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: totem_right
    artifact-name: totem_ergol_2tk_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y

    # Azerty + thumb-taps config
  - board: xiao_ble
    shield: totem_left
    artifact-name: totem_azerty_tt_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: totem_right
    artifact-name: totem_azerty_tt_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, Ergo-L + Hummingbird config
  - board: xiao_ble
    shield: totem_left
    artifact-name: totem_ergol_hummingbird_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: totem_right
    artifact-name: totem_ergol_hummingbird_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DKEYMAP_FILE=/__w/zmk-config-selenium/zmk-config-selenium/keymaps/totem.keymap
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y
