# This file describes the firmwares that are built by the GitHub Actions CI.
#  - all supported keebs have a dedicated firmware implementing `selenium.keymap`

include:

  ###
  # ProMicro-Based Keyboards
  #
  # These keebs consist in two parts:
  #  - a shield = the keyboard itself
  #  - a board = the micro-controller unit (MCU), which can be:
  #    - nice_nano@2 (nice!nano v2)
  #    - sparkfun_pro_micro_rp2040
  #    - xiao_ble
  #    - ... and many others
  #
  # => make sure the `board` field matches the MCU on your keyboard
  ##

  # Totem + XIAO BLE
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_left
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_right
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
