CONFIG_ZMK_USB_LOGGING=n
# This is required to fix "stuck key" issues with some key combinations
# For example, when quickly pressing/releasing "space" and then "shift",
# the "space" key can get stuck until the left half is reset.
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
