on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    uses: ./.github/workflows/zmk-build-user-config.yml
    with:
      archive_name: firmware-tester-selenium
      build_matrix_path: ci.yaml
  build:
    # Only run `build` after `ci` as `build-user-config.yml` does not seem
    # to support concurrent runs
    needs: ci
    uses: ./.github/workflows/zmk-build-user-config.yml
    with:
      archive_name: firmware-selenium
