name: Build ZMK firmwares
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: Nuclear-Squid/zmk/.github/workflows/build-user-config.yml@aekeynox
    with:
      archive_name: firmware-selenium
