on: [push, pull_request]

jobs:
  ci:
    name: "ci: Build test firmwares with various configuration options"
    if: github.repository_owner == 'OneDeadKey' || github.repository_owner == 'cfergeau'
    uses: ./.github/workflows/zmk-build-user-config.yml
    with:
      archive_name: firmware-tester-selenium
      build_matrix_path: ci.yaml
